[build]
  base = "client"
  publish = "build"
  command = "npm ci && npm run build"


[build.environment]
  NODE_VERSION = "20.11.0"
  NODE_ENV = "production"

[context.production]
  ignore = "false"
